spring:
  security:
    user:
      name: api
      password: api
  rabbitmq:
    host: mlqs-rabbitmq
    port: 5672
    #host: host.docker.internal
    #port: 7070
    username: user
    password: password
    cache:
      #channel:
      #  size: 0 #maximum number of allowed channels - default 0 (channel limiting not enabled)
      connection:
        mode: channel
        size: 1 #maximum number of connections in a cache.
    virtual-host: compose
    exchanges:
      random-events: mlqs.dummy.data.generator.random.event.ex

files:
  employees:
    path: "/opt/ww/mlqs-dummy-data-generator/output/employees.csv"
  images:
    path: "/opt/ww/mlqs-dummy-data-generator/output/images"

jasypt:
  encryptor:
    password: ${JASYPT_PASS}
